annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Elemental CRDs
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-elemental-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/provides-gvr: elemental.cattle.io/v1beta1
  catalog.cattle.io/release-name: elemental-operator-crds
apiVersion: v2
appVersion: 1.2.5
description: A Helm chart for deploying Rancher Elemental Operator CRDs
name: elemental-operator-crds
version: 1.2.5
